feat: ioredis is added for support cluster
jambonz/realtimedb-helpers pull request #43
Opened 2023-05-26 07:13 UTC by xquanluu

#42

2023-05-26 15:01 UTC, davehorton requested changes

2023-05-27 07:21 UTC, xquanluu commented on README.md
> +If redis cluster is used:
fixed

2023-05-27 07:21 UTC, xquanluu commented on README.md
> +```
fixed

2023-05-27 14:39 UTC, davehorton approved these changes

2023-05-27 14:39 UTC, merged

2023-05-27 14:43 UTC, davehorton commented
published as @jambonz/realtimedb-helpers (0.8.0) @xquanluu